server:
  port: 8083

spring:
  application:
    name: MS-RANKING
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: rankingdb
springdoc:
  api-docs:
    path: /api-docs
  show-actuator: false
  packages-to-scan: com.ms.rating.service.controller
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka