server:
  port: 8081
spring:
  application:
    name: MS-USER
  datasource:
    url: jdbc:mysql://localhost:3308/userdb
    username: root
    password: netec123
    driver: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
#http://localhost:8081/swagger-ui/index.html
springdoc:
  api-docs:
    path: /api-docs
  show-actuator: false
  package-ot-scan: com.ms.user.controller
control:
  exception:
    personalizada: Se genero un error de negocio
    system: Se genero un error del sistema
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
resilience4j:
  circuitBreaker:
    instances:
      responseCircuitBreaker:
        registerHealIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnable: true
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED