server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3308/userdb
    username: root
    password: netec123
    driver: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
springdoc:
  api-docs:
    path: /api-netec
  show-actuator: false
  packages-to-scan: com.ms.user.controller