version: '3.7'

services:
  activemq:
    image: rmohr/activemq:5.12.1
    container_name: activemq
    environment:
      - "TZ=Europe/Amsterdam"
    volumes:
      - "~/docker-config/activemq/activemq.xml:/conf/activemq.xml"
    ports:
      - "61613:61613" # broker (admin:adminactivemq)(amq:amq)
      - "61616:61616" # broker (admin:adminactivemq)(amq:amq)
      - "8161:8161"   # web    http://boot2docker:8161/admin (admin:admin)